export const langMap: Record<string, string> = {
  ace: 'Achinese',
  ada: 'Adangme',
  afr: 'Afrikaans',
  aii: 'Assyrian Neo-Aramaic',
  als: 'Tosk Albanian',
  amh: 'Amharic',
  arb: 'Standard Arabic',
  ayr: 'Central Aymara',
  azj: 'North Azerbaijani',
  bam: 'Bambara',
  ban: 'Balinese',
  bci: 'Baoulé',
  bcl: 'Central Bikol',
  bel: 'Belarusian',
  bem: 'Bemba',
  ben: 'Bengali',
  bho: 'Bhojpuri',
  bin: 'Bini',
  bod: 'Tibetan',
  bos: 'Bosnian',
  bug: 'Buginese',
  bul: 'Bulgarian',
  bum: 'Bulu',
  cat: 'Catalan',
  ceb: 'Cebuano',
  ces: 'Czech',
  cjk: 'Chokwe',
  ckb: 'Central Kurdish',
  cmn: 'Mandarin Chinese',
  dan: 'Danish',
  deu: 'German',
  dip: 'Northeastern Dinka',
  dyu: 'Dyula',
  ekk: 'Standard Estonian',
  ell: 'Modern Greek',
  emk: 'Eastern Maninkakan',
  eng: 'English',
  epo: 'Esperanto',
  ewe: 'Ewe',
  fin: 'Finnish',
  fon: 'Fon',
  fra: 'French',
  fuf: 'Pular',
  fuv: 'Nigerian Fulfulde',
  gaa: 'Ga',
  glg: 'Galician',
  guj: 'Gujarati',
  hat: 'Haitian',
  hau: 'Hausa',
  heb: 'Hebrew',
  hil: 'Hiligaynon',
  hin: 'Hindi',
  hms: 'Southern Qiandong Miao',
  hnj: 'Hmong Njua',
  hrv: 'Croatian',
  hun: 'Hungarian',
  hye: 'Armenian',
  ibb: 'Ibibio',
  ibo: 'Igbo',
  iii: 'Sichuan Yi',
  ilo: 'Iloko',
  ind: 'Indonesian',
  ita: 'Italian',
  jav: 'Javanese',
  jpn: 'Japanese',
  kan: 'Kannada',
  kat: 'Georgian',
  kaz: 'Kazakh',
  kbd: 'Kabardian',
  kbp: 'Kabiyè',
  kde: 'Makonde',
  khk: 'Halh Mongolian',
  khm: 'Khmer',
  kin: 'Kinyarwanda',
  kir: 'Kirghiz',
  kmb: 'Kimbundu',
  knc: 'Central Kanuri',
  kng: 'Koongo',
  koi: 'Komi-Permyak',
  kor: 'Korean',
  lao: 'Lao',
  lin: 'Lingala',
  lit: 'Lithuanian',
  lua: 'Luba-Lulua',
  lug: 'Ganda',
  lun: 'Lunda',
  lvs: 'Standard Latvian',
  mad: 'Madurese',
  mag: 'Magahi',
  mai: 'Maithili',
  mal: 'Malayalam',
  mar: 'Marathi',
  men: 'Mende',
  min: 'Minangkabau',
  mkd: 'Macedonian',
  mos: 'Mossi',
  mya: 'Burmese',
  ndo: 'Ndonga',
  nds: 'Low German',
  nhn: 'Central Nahuatl',
  nld: 'Dutch',
  nno: 'Norwegian Nynorsk',
  nob: 'Norwegian Bokmål',
  npi: 'Nepali',
  nso: 'Pedi',
  nya: 'Nyanja',
  nyn: 'Nyankole',
  pam: 'Pampanga',
  pan: 'Panjabi',
  pbu: 'Northern Pashto',
  pes: 'Iranian Persian',
  plt: 'Plateau Malagasy',
  pol: 'Polish',
  por: 'Portuguese',
  prs: 'Dari',
  qug: 'Chimborazo Highland Quichua',
  quy: 'Ayacucho Quechua',
  quz: 'Cusco Quechua',
  rmn: 'Balkan Romani',
  ron: 'Romanian',
  run: 'Rundi',
  rup: 'Macedo-Romanian',
  rus: 'Russian',
  sag: 'Sango',
  sat: 'Santali',
  sco: 'Scots',
  shn: 'Shan',
  sin: 'Sinhala',
  skr: 'Saraiki',
  slk: 'Slovak',
  slv: 'Slovenian',
  sna: 'Shona',
  snk: 'Soninke',
  som: 'Somali',
  sot: 'Southern Sotho',
  spa: 'Spanish',
  src: 'Logudorese Sardinian',
  srp: 'Serbian',
  ssw: 'Swati',
  suk: 'Sukuma',
  sun: 'Sundanese',
  swe: 'Swedish',
  swh: 'Swahili',
  tam: 'Tamil',
  tat: 'Tatar',
  tel: 'Telugu',
  tem: 'Timne',
  tgk: 'Tajik',
  tgl: 'Tagalog',
  tha: 'Thai',
  tir: 'Tigrinya',
  tiv: 'Tiv',
  toi: 'Tonga',
  tpi: 'Tok Pisin',
  tsn: 'Tswana',
  tso: 'Tsonga',
  tuk: 'Turkmen',
  tur: 'Turkish',
  tzm: 'Central Atlas Tamazight',
  uig: 'Uighur',
  ukr: 'Ukrainian',
  umb: 'Umbundu',
  urd: 'Urdu',
  uzn: 'Northern Uzbek',
  vec: 'Venetian',
  ven: 'Venda',
  vie: 'Vietnamese',
  vmw: 'Makhuwa',
  war: 'Waray',
  wol: 'Wolof',
  xho: 'Xhosa',
  yao: 'Yao',
  ydd: 'Eastern Yiddish',
  yor: 'Yoruba',
  zgh: 'Standard Moroccan Tamazight',
  zlm: 'Malay',
  zul: 'Zulu',
  zyb: 'Yongbei Zhuang',
};
