export const BOOK_LANGUAGE = {
  ace: 'Achinese',
  ada: 'Adangme',
  afr: 'Afrikaans',
  aii: 'Assyrian Neo-Aramaic',
  als: 'Tosk Albanian',
  amh: 'Amharic',
  arb: 'العربية',
  ayr: 'Central Aymara',
  azj: 'North Azerbaijani',
  bam: 'Bambara',
  ban: 'Balinese',
  bci: 'Baoulé',
  bcl: 'Central Bikol',
  bel: 'Беларуская',
  bem: 'Bemba',
  ben: 'Bengali',
  bho: 'Bhojpuri',
  bin: 'Bini',
  bod: 'Tibetan',
  bos: 'Bosnian',
  bug: 'Buginese',
  bul: 'Български',
  bum: 'Bulu',
  cat: 'Catalan',
  ceb: 'Cebuano',
  ces: 'Čeština',
  cjk: 'Chokwe',
  ckb: 'Central Kurdish',
  cmn: '中文',
  dan: 'Dansk',
  deu: 'Deutsch',
  dip: 'Northeastern Dinka',
  dyu: 'Dyula',
  ekk: 'Eesti',
  ell: 'Ελληνικά',
  emk: 'Eastern Maninkakan',
  eng: 'English',
  epo: 'Esperanto',
  ewe: 'Ewe',
  fin: 'Suomi',
  fon: 'Fon',
  fra: 'Français',
  fuf: 'Pular',
  fuv: 'Nigerian Fulfulde',
  gaa: 'Ga',
  glg: 'Galician',
  guj: 'Gujarati',
  hat: 'Haitian',
  hau: 'Hausa',
  heb: 'עברית',
  hil: 'Hiligaynon',
  hin: 'हिन्दी',
  hms: 'Southern Qiandong Miao',
  hnj: 'Hmong Njua',
  hrv: 'Hrvatski',
  hun: 'Magyar',
  hye: 'Armenian',
  ibb: 'Ibibio',
  ibo: 'Igbo',
  iii: 'Sichuan Yi',
  ilo: 'Iloko',
  ind: 'Bahasa Indonesia',
  ita: 'Italiano',
  jav: 'Javanese',
  jpn: '日本語',
  kan: 'Kannada',
  kat: 'Georgian',
  kaz: 'Қазақша',
  kbd: 'Kabardian',
  kbp: 'Kabiyè',
  kde: 'Makonde',
  khk: 'Halh Mongolian',
  khm: 'Khmer',
  kin: 'Kinyarwanda',
  kir: 'Kirghiz',
  kmb: 'Kimbundu',
  knc: 'Central Kanuri',
  kng: 'Koongo',
  koi: 'Komi-Permyak',
  kor: '한국어',
  lao: 'Lao',
  lin: 'Lingala',
  lit: 'Lietuvių',
  lua: 'Luba-Lulua',
  lug: 'Ganda',
  lun: 'Lunda',
  lvs: 'Latviešu',
  mad: 'Madurese',
  mag: 'Magahi',
  mai: 'Maithili',
  mal: 'Malayalam',
  mar: 'Marathi',
  men: 'Mende',
  min: 'Minangkabau',
  mkd: 'Macedonian',
  mos: 'Mossi',
  mya: 'Burmese',
  ndo: 'Ndonga',
  nds: 'Low German',
  nhn: 'Central Nahuatl',
  nld: 'Nederlands',
  nno: 'Norsk nynorsk',
  nob: 'Norsk bokmål',
  npi: 'Nepali',
  nso: 'Pedi',
  nya: 'Nyanja',
  nyn: 'Nyankole',
  pam: 'Pampanga',
  pan: 'Panjabi',
  pbu: 'Northern Pashto',
  pes: 'فارسی',
  plt: 'Plateau Malagasy',
  pol: 'Polski',
  por: 'Português',
  prs: 'Dari',
  qug: 'Chimborazo Highland Quichua',
  quy: 'Ayacucho Quechua',
  quz: 'Cusco Quechua',
  rmn: 'Balkan Romani',
  ron: 'Română',
  run: 'Rundi',
  rup: 'Macedo-Romanian',
  rus: 'Русский',
  sag: 'Sango',
  sat: 'Santali',
  sco: 'Scots',
  shn: 'Shan',
  sin: 'Sinhala',
  skr: 'Saraiki',
  slk: 'Slovenčina',
  slv: 'Slovenščina',
  sna: 'Shona',
  snk: 'Soninke',
  som: 'Somali',
  sot: 'Southern Sotho',
  spa: 'Español',
  src: 'Logudorese Sardinian',
  srp: 'Српски',
  ssw: 'Swati',
  suk: 'Sukuma',
  sun: 'Sundanese',
  swe: 'Svenska',
  swh: 'Swahili',
  tam: 'Tamil',
  tat: 'Tatar',
  tel: 'Telugu',
  tem: 'Timne',
  tgk: 'Tajik',
  tgl: 'Tagalog',
  tha: 'ไทย',
  tir: 'Tigrinya',
  tiv: 'Tiv',
  toi: 'Tonga',
  tpi: 'Tok Pisin',
  tsn: 'Tswana',
  tso: 'Tsonga',
  tuk: 'Turkmen',
  tur: 'Türkçe',
  tzm: 'Central Atlas Tamazight',
  uig: 'Uighur',
  ukr: 'Українська',
  umb: 'Umbundu',
  urd: 'Urdu',
  uzn: 'Northern Uzbek',
  vec: 'Venetian',
  ven: 'Venda',
  vie: 'Tiếng Việt',
  vmw: 'Makhuwa',
  war: 'Waray',
  wol: 'Wolof',
  xho: 'Xhosa',
  yao: 'Yao',
  ydd: 'Eastern Yiddish',
  yor: 'Yoruba',
  zgh: 'Standard Moroccan Tamazight',
  zlm: 'Malay',
  zul: 'Zulu',
  zyb: 'Yongbei Zhuang',
} as const;

export const ISO_639_1_TO_3: Record<string, string> = {
  af: 'afr',
  am: 'amh',
  ar: 'arb',
  az: 'azj',
  be: 'bel',
  bg: 'bul',
  bm: 'bam',
  bn: 'ben',
  bo: 'bod',
  bs: 'bos',
  ca: 'cat',
  cs: 'ces',
  da: 'dan',
  de: 'deu',
  ee: 'ewe',
  el: 'ell',
  en: 'eng',
  eo: 'epo',
  es: 'spa',
  et: 'ekk',
  fa: 'pes',
  ff: 'fuv',
  fi: 'fin',
  fr: 'fra',
  gl: 'glg',
  gu: 'guj',
  ha: 'hau',
  he: 'heb',
  hi: 'hin',
  hr: 'hrv',
  ht: 'hat',
  hu: 'hun',
  hy: 'hye',
  id: 'ind',
  ig: 'ibo',
  ii: 'iii',
  it: 'ita',
  ja: 'jpn',
  jv: 'jav',
  ka: 'kat',
  kk: 'kaz',
  km: 'khm',
  kn: 'kan',
  ko: 'kor',
  kr: 'knc',
  ku: 'ckb',
  ky: 'kir',
  lg: 'lug',
  ln: 'lin',
  lo: 'lao',
  lt: 'lit',
  lv: 'lvs',
  mk: 'mkd',
  ml: 'mal',
  mn: 'khk',
  mr: 'mar',
  ms: 'zlm',
  my: 'mya',
  nb: 'nob',
  ne: 'npi',
  ng: 'ndo',
  nl: 'nld',
  nn: 'nno',
  no: 'nob',
  ny: 'nya',
  pa: 'pan',
  pl: 'pol',
  ps: 'pbu',
  pt: 'por',
  qu: 'quy',
  rn: 'run',
  ro: 'ron',
  ru: 'rus',
  rw: 'kin',
  sg: 'sag',
  si: 'sin',
  sk: 'slk',
  sl: 'slv',
  sn: 'sna',
  so: 'som',
  sq: 'als',
  sr: 'srp',
  ss: 'ssw',
  st: 'sot',
  su: 'sun',
  sv: 'swe',
  sw: 'swh',
  ta: 'tam',
  te: 'tel',
  tg: 'tgk',
  th: 'tha',
  ti: 'tir',
  tk: 'tuk',
  tl: 'tgl',
  tn: 'tsn',
  tr: 'tur',
  ts: 'tso',
  tt: 'tat',
  ug: 'uig',
  uk: 'ukr',
  ur: 'urd',
  uz: 'uzn',
  ve: 'ven',
  vi: 'vie',
  wo: 'wol',
  xh: 'xho',
  yi: 'ydd',
  yo: 'yor',
  za: 'zyb',
  zh: 'cmn',
  zu: 'zul',
};
